#! /bin/sh

if [ ! $(sudo echo 0) ]; then
	echo "You have to use sudo for this command"
	exit 1
fi

if [ $# -eq 0 ]; then
	echo "Give an argument please"
	exit 1
fi

#zone description in config
echo "zone \"$1.sander-vanthillo.sb.uclllabs.be\" {
	type master;
	file \"/etc/bind/zones/mrt-zones/db.$1.sander-vanthillo.sb.uclllabs.be\";
};" >> /etc/bind/named.conf.mrt-zones

#create a new zone file
touch /etc/bind/zones/mrt-zones/db.$1.sander-vanthillo.sb.uclllabs.be

#add settings to the new zone file
echo "\$TTL 300
@ IN SOA ns.$1.sander-vanthillo.sb.uclllabs.be. host.sander-vanthillo.sb.uclllabs.be. (
	1 ; Serial
	900 ; Refresh
	120 ; Retry
	900 ; Expire
	300 ) ; Default TTL

@	IN	NS	ns.sander-vanthillo.sb.uclllabs.be." > /etc/bind/zones/mrt-zones/db.$1.sander-vanthillo.sb.uclllabs.be

#add records of the new subzone to the main zone
echo "$1	IN	NS	ns.sander-vanthillo.sb.uclllabs.be." >> /etc/bind/zones/db.sander-vanthillo.sb.uclllabs.be
echo "$1	IN	A	193.191.177.205" >> /etc/bind/zones/db.sander-vanthillo.sb.uclllabs.be

ID=$(echo | cat /etc/bind/zones/db.sander-vanthillo.sb.uclllabs.be | grep 'Serial' | grep -o '[0-9]*')
echo $ID
sed -i "s/$ID/$(($ID + 1))/g" /etc/bind/zones/db.sander-vanthillo.sb.uclllabs.be

#reload
rndc reload
