---
  - name: "http script"
    hosts: localhost
    connection: local
    vars_files:
        - vars/default.yml
    tasks:

    - name: "grep"
      shell: "grep {{ PREFIX }}[[:space:]]*IN[[:space:]]*A /etc/bind/zones/mrt-zones/db.{{ SUBDOMAIN }}.sander-vanthillo.sb.uclllabs.be"
      register: "output"

    - debug: var=output.stdout_lines

    - name: Create directory in html
      file:
        path: "/var/www/html/{{ PREFIX }}.{{SUBDOMAIN }}"
        state: directory
        owner: "root"
        mode: '0755'

    - name: Copy index test page
      template:
        src: "files/index.html.j2"
        dest: "/var/www/html/{{ PREFIX }}.{{ SUBDOMAIN }}/index.html"


    - name: "echo"
      shell: "echo welcome {{ PREFIX }}.{{ SUBDOMAIN }} > /var/www/html/{{ PREFIX }}.{{ SUBDOMAIN }}/index.html"
      register: "output"


    - name: Set up virtualhost
      template:
        src: "files/httpscript.conf.j2"
        dest: "/etc/apache2/sites-available/{{ PREFIX }}.{{ SUBDOMAIN}}.conf"

    - name: Enable virtualhost
      shell: /usr/sbin/a2ensite {{ PREFIX }}.{{ SUBDOMAIN}}.conf
      notify: Reload Apache

    handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
