#!/bin/bash

function stop() {
        iptables-restore /etc/network/iptables.empty
        ip6tables-restore /etc/network/ip6tables.empty
}

function start() {
        iptables-restore /etc/network/iptables.rules
        ip6tables-restore /etc/network/ip6tables.rules
}

case $1 in
start)
        start
        ;;
stop)
        stop
        ;;
restart)
        stop
        start
        ;;
*)
        exit 1;
esac
